In [40]:

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

In [41]:
sentences = [
 "I love this product",
 "This movie made me smile",
 "Service was friendly and quick",
 "Today felt bright and happy",
 "This is the best day",
 "Absolutely fantastic experience",
 "I enjoyed every single moment",
 "Great job, well done",
 "The food tasted delicious",
 "Totally recommend to everyone",
 "Very satisfied with results",
 "This worked better than expected",
 "Amazing quality and value",
 "Such a pleasant surprise",
 "I feel positive about this",
 "I hate this product",
 "This movie bored me",
 "Service was rude and slow",
 "Today was cold and lonely",
 "This is the worst day",
 "Terrible experience overall",
 "I regret buying this",
 "Very disappointed with results",
 "The food tasted awful",
 "Do not recommend this",
 "It broke after one use",
 "Not worth the money",
 "Utterly frustrating and annoying",
 "I feel negative about this",
 "Such a waste of time",
]
labels = [1]*15 + [0]*15
labels = np.array(labels)

In [42]:
Vocab_size=2000
token=Tokenizer(num_words=Vocab_size,oov_token="")
token.fit_on_texts(sentences)
sequences=token.texts_to_sequences(sentences)
maxLength=max(len(s) for s in sequences)
X=pad_sequences(sequences,maxlen=maxLength,padding="post")
y=labels
print("X value is :",X)
print("\n")
print("Y value is :",Y)
print("matrix of the X is :",X[0])


X value is : [[ 3 26  2  7  0]
 [ 2  8 27  9 28]
 [10  6 29  4 30]
 [11 31 32  4 33]
 [ 2 12  5 34 13]
 [35 36 14  0  0]
 [ 3 37 38 39 40]
 [41 42 43 44  0]
 [ 5 15 16 45  0]
 [46 17 47 48  0]
 [18 49 19 20  0]
 [ 2 50 51 52 53]
 [54 55  4 56  0]
 [21 22 57 58  0]
 [ 3 23 59 24  2]
 [ 3 60  2  7  0]
 [ 2  8 61  9  0]
 [10  6 62  4 63]
 [11  6 64  4 65]
 [ 2 12  5 66 13]
 [67 14 68  0  0]
 [ 3 69 70  2  0]
 [18 71 19 20  0]
 [ 5 15 16 72  0]
 [73 25 17  2  0]
 [74 75 76 77 78]
 [25 79  5 80  0]
 [81 82  4 83  0]
 [ 3 23 84 24  2]
 [21 22 85 86 87]]


Y value is : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
matrix of the X is : [ 3 26  2  7  0]


In [43]:

embed_dim = 16
rnn_units = 8

In [44]:
input=Input(shape=(maxLength,),dtype="int32",name="input")
x=Embedding(input_dim=Vocab_size,output_dim=embed_dim,mask_zero=True,name="Embedding")(input)
Rnn=SimpleRNN(units=rnn_units,name="SimpleRNN",return_sequences=False,return_state=False)
X_last=Rnn(X)
Output=Dense(1,activation='sigmoid',name="output")(X_last)
model=Model(inputs=input,outputs=Output)
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

ValueError: Input 0 with name 'None' of layer 'SimpleRNN' is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (30, 5)

In [45]:
model.fit(X,y ,epochs=20,batch_size=8,verbose=1)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.4667 - loss: 0.6882
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7667 - loss: 0.6742
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9000 - loss: 0.6606
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9000 - loss: 0.6490
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9000 - loss: 0.6359
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9000 - loss: 0.6228
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9000 - loss: 0.6079
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9000 - loss: 0.5928
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9000 - loss: 0.5773
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9000 - loss: 0.5610
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9333 - loss: 0.5437
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9667 - loss: 0.5250
E